# .streamlit/config.toml
[server]
headless = true
enableStaticServing = true

[theme]
primaryColor="#3c1c5c"
backgroundColor="#f3e9f7"
secondaryBackgroundColor="#3c1c5c"
textColor="#FFFFFF"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
